// src/context/LanguageContext.jsx
// ─────────────────────────────────────────────────────────────────────────────
// Ek baar language switch karo → poori app mein apply ho jaye
// localStorage mein save hota hai → page refresh pe bhi yaad rahe
// Saari Indian languages support hain + dropdown switcher
// ─────────────────────────────────────────────────────────────────────────────

import { createContext, useContext, useState, useRef, useEffect } from "react";

// ── All Indian Languages List ─────────────────────────────────────────────────
export const LANGUAGES = [
  { code: "en", label: "English", native: "English" },
  { code: "hi", label: "Hindi", native: "हिंदी" },
  { code: "bn", label: "Bengali", native: "বাংলা" },
  { code: "te", label: "Telugu", native: "తెలుగు" },
  { code: "mr", label: "Marathi", native: "मराठी" },
  { code: "ta", label: "Tamil", native: "தமிழ்" },
  { code: "gu", label: "Gujarati", native: "ગુજરાતી" },
  { code: "kn", label: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", label: "Malayalam", native: "മലയാളം" },
  { code: "pa", label: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "or", label: "Odia", native: "ଓଡ଼ିଆ" },
  { code: "as", label: "Assamese", native: "অসমীয়া" },
  { code: "ur", label: "Urdu", native: "اردو" },
  { code: "sa", label: "Sanskrit", native: "संस्कृतम्" },
];

// ── Translations ──────────────────────────────────────────────────────────────
export const translations = {
  en: {
    // Navbar
    home: "Home",
    services: "Services",
    doctors: "Doctors",
    about: "About",
    contact: "Contact",
    login: "Login",
    registerFree: "Register Free",
    myDashboard: "My Dashboard →",
    logout: "Logout",

    // Hero
    tagline: "India's #1 Hospital Management Platform",
    heroTitle1: "Your Health,",
    heroTitle2: "Our Priority",
    heroDesc:
      "Book appointments, consult top doctors, and manage your health journey — all in one place.",
    bookAppointment: "Book Appointment →",
    exploreServices: "Explore Services",
    statDoctors: "Doctors",
    statPatients: "Patients",
    statSatisfaction: "Satisfaction",

    // Sections
    whatWeOffer: "What We Offer",
    ourSpecializations: "Our Specializations",
    bookNow: "Book Now →",
    meetTheTeam: "Meet The Team",
    ourTopDoctors: "Our Top Doctors",
    allPaymentMethods: "All Payment Methods",
    contactUs: "Contact Us",
    address: "📍 123 Medical Hub, New Delhi, India",
    phone: "📞 +91 98765 43210",
    yourName: "Your Name",
    yourEmail: "Your Email",
    message: "Message",
    sendMessage: "Send Message",
    messageSent: "✅ Message sent!",
    nextAppointment: "Next Appointment",
    confirmed: "✅ Confirmed",

    // Login
    signIn: "Sign In",
    signingIn: "Signing in…",
    patientLogin: "Patient Login",
    accessYourAccount: "Access your account and manage your health.",
    email: "Email",
    password: "Password",
    dontHaveAccount: "Don't have an account?",
    register: "Register",
    loginFailed: "Login failed. Please try again.",

    // Doctor Login
    doctorPortal: "Doctor Portal",
    doctorAccess: "🩺 Doctor Access",
    doctorSignIn: "Doctor Sign In",
    doctorRegistration: "Doctor Registration",
    enterDoctorCredentials: "Enter your doctor credentials",
    fillDetailsToRegister: "Fill in details to register",
    fullName: "Full Name",
    phone2: "Phone",
    experienceYears: "Experience (years)",
    department: "Department",
    selectDepartment: "— Select Department —",
    specialization: "Specialization",
    consultationFee: "Consultation Fee (₹)",
    accessDoctorDashboard: "Access Doctor Dashboard →",
    pleaseWait: "Please wait…",
    registerArrow: "Register →",
    registrationSuccess: "Registration successful! Please login.",

    // Admin Login
    adminControl: "Admin Control Panel",
    adminAccess: "🔐 Admin Access",
    adminSignIn: "Admin Sign In",
    restrictedToAdmins: "Restricted to administrators only",
    adminEmail: "Admin Email",
    verifying: "Verifying…",
    accessAdminPanel: "Access Admin Panel →",

    // Register
    joinMedicore: "Join MediCore Today",
    createPatientAccount: "Create Patient Account",
    alreadyHaveAccount: "Already have an account?",
    registering: "Registering…",
    registrationFailed: "Registration failed. Try again.",

    // Password
    showPassword: "Show password",
    hidePassword: "Hide password",

    // Dashboard
    bookAppointmentTab: "Book Appointment",
    myAppointments: "My Appointments",
    newAppointment: "New Appointment",
    selectDoctor: "Select Doctor",
    chooseDoctor: "— Choose a Doctor —",
    date: "Date",
    time: "Time",
    notes: "Notes (Optional)",
    notesPlaceholder: "Describe your symptoms...",
    bookingBtn: "📅 Book Appointment",
    booking: "Booking…",
    availableDoctors: "Available Doctors",
    noAppointmentsYet: "No appointments yet.",

    // Language
    language: "Language",
    selectLanguage: "Select Language",
  },

  hi: {
    home: "होम",
    services: "सेवाएं",
    doctors: "डॉक्टर",
    about: "हमारे बारे में",
    contact: "संपर्क",
    login: "लॉगिन",
    registerFree: "मुफ्त रजिस्टर करें",
    myDashboard: "मेरा डैशबोर्ड →",
    logout: "लॉगआउट",
    tagline: "भारत का #1 अस्पताल प्रबंधन प्लेटफॉर्म",
    heroTitle1: "आपका स्वास्थ्य,",
    heroTitle2: "हमारी प्राथमिकता",
    heroDesc: "अपॉइंटमेंट बुक करें, शीर्ष डॉक्टरों से परामर्श लें — सब एक जगह।",
    bookAppointment: "अपॉइंटमेंट बुक करें →",
    exploreServices: "सेवाएं देखें",
    statDoctors: "डॉक्टर",
    statPatients: "मरीज़",
    statSatisfaction: "संतुष्टि",
    whatWeOffer: "हम क्या प्रदान करते हैं",
    ourSpecializations: "हमारी विशेषज्ञताएं",
    bookNow: "अभी बुक करें →",
    meetTheTeam: "हमारी टीम से मिलें",
    ourTopDoctors: "हमारे शीर्ष डॉक्टर",
    allPaymentMethods: "सभी भुगतान विधियां",
    contactUs: "हमसे संपर्क करें",
    address: "📍 123 मेडिकल हब, नई दिल्ली, भारत",
    phone: "📞 +91 98765 43210",
    yourName: "आपका नाम",
    yourEmail: "आपका ईमेल",
    message: "संदेश",
    sendMessage: "संदेश भेजें",
    messageSent: "✅ संदेश भेज दिया गया!",
    nextAppointment: "अगला अपॉइंटमेंट",
    confirmed: "✅ पुष्टि हुई",
    signIn: "साइन इन",
    signingIn: "साइन इन हो रहा है…",
    patientLogin: "मरीज़ लॉगिन",
    accessYourAccount: "अपना खाता एक्सेस करें और स्वास्थ्य प्रबंधित करें।",
    email: "ईमेल",
    password: "पासवर्ड",
    dontHaveAccount: "खाता नहीं है?",
    register: "रजिस्टर करें",
    loginFailed: "लॉगिन विफल। कृपया पुनः प्रयास करें।",
    doctorPortal: "डॉक्टर पोर्टल",
    doctorAccess: "🩺 डॉक्टर एक्सेस",
    doctorSignIn: "डॉक्टर साइन इन",
    doctorRegistration: "डॉक्टर पंजीकरण",
    enterDoctorCredentials: "अपनी डॉक्टर लॉगिन जानकारी दर्ज करें",
    fillDetailsToRegister: "पंजीकरण के लिए विवरण भरें",
    fullName: "पूरा नाम",
    phone2: "फोन",
    experienceYears: "अनुभव (वर्ष)",
    department: "विभाग",
    selectDepartment: "— विभाग चुनें —",
    specialization: "विशेषज्ञता",
    consultationFee: "परामर्श शुल्क (₹)",
    accessDoctorDashboard: "डॉक्टर डैशबोर्ड एक्सेस करें →",
    pleaseWait: "कृपया प्रतीक्षा करें…",
    registerArrow: "रजिस्टर करें →",
    registrationSuccess: "पंजीकरण सफल! कृपया लॉगिन करें।",
    adminControl: "एडमिन कंट्रोल पैनल",
    adminAccess: "🔐 एडमिन एक्सेस",
    adminSignIn: "एडमिन साइन इन",
    restrictedToAdmins: "केवल प्रशासकों के लिए",
    adminEmail: "एडमिन ईमेल",
    verifying: "सत्यापन हो रहा है…",
    accessAdminPanel: "एडमिन पैनल एक्सेस करें →",
    joinMedicore: "आज MediCore से जुड़ें",
    createPatientAccount: "मरीज़ खाता बनाएं",
    alreadyHaveAccount: "पहले से खाता है?",
    registering: "रजिस्टर हो रहा है…",
    registrationFailed: "पंजीकरण विफल। पुनः प्रयास करें।",
    showPassword: "पासवर्ड दिखाएं",
    hidePassword: "पासवर्ड छुपाएं",
    bookAppointmentTab: "अपॉइंटमेंट बुक करें",
    myAppointments: "मेरे अपॉइंटमेंट",
    newAppointment: "नया अपॉइंटमेंट",
    selectDoctor: "डॉक्टर चुनें",
    chooseDoctor: "— डॉक्टर चुनें —",
    date: "तारीख",
    time: "समय",
    notes: "नोट्स (वैकल्पिक)",
    notesPlaceholder: "अपने लक्षण बताएं...",
    bookingBtn: "📅 अपॉइंटमेंट बुक करें",
    booking: "बुकिंग हो रही है…",
    availableDoctors: "उपलब्ध डॉक्टर",
    noAppointmentsYet: "अभी तक कोई अपॉइंटमेंट नहीं।",
    language: "भाषा",
    selectLanguage: "भाषा चुनें",
  },

  bn: {
    home: "হোম",
    services: "সেবা",
    doctors: "ডাক্তার",
    about: "আমাদের সম্পর্কে",
    contact: "যোগাযোগ",
    login: "লগইন",
    registerFree: "বিনামূল্যে নিবন্ধন",
    myDashboard: "আমার ড্যাশবোর্ড →",
    logout: "লগআউট",
    tagline: "ভারতের #1 হাসপাতাল ব্যবস্থাপনা প্ল্যাটফর্ম",
    heroTitle1: "আপনার স্বাস্থ্য,",
    heroTitle2: "আমাদের অগ্রাধিকার",
    heroDesc: "অ্যাপয়েন্টমেন্ট বুক করুন, শীর্ষ ডাক্তারদের সাথে পরামর্শ করুন।",
    bookAppointment: "অ্যাপয়েন্টমেন্ট বুক করুন →",
    exploreServices: "সেবা দেখুন",
    statDoctors: "ডাক্তার",
    statPatients: "রোগী",
    statSatisfaction: "সন্তুষ্টি",
    signIn: "সাইন ইন",
    signingIn: "সাইন ইন হচ্ছে…",
    patientLogin: "রোগী লগইন",
    accessYourAccount: "আপনার অ্যাকাউন্ট অ্যাক্সেস করুন।",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    dontHaveAccount: "অ্যাকাউন্ট নেই?",
    register: "নিবন্ধন করুন",
    loginFailed: "লগইন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।",
    showPassword: "পাসওয়ার্ড দেখান",
    hidePassword: "পাসওয়ার্ড লুকান",
    fullName: "পুরো নাম",
    phone2: "ফোন",
    department: "বিভাগ",
    selectDepartment: "— বিভাग নির্বাচন করুন —",
    specialization: "বিশেষজ্ঞতা",
    consultationFee: "পরামর্শ ফি (₹)",
    pleaseWait: "অনুগ্রহ করে অপেক্ষা করুন…",
    bookAppointmentTab: "অ্যাপয়েন্টমেন্ট বুক করুন",
    myAppointments: "আমার অ্যাপয়েন্টমেন্ট",
    newAppointment: "নতুন অ্যাপয়েন্টমেন্ট",
    selectDoctor: "ডাক্তার নির্বাচন করুন",
    chooseDoctor: "— ডাক্তার নির্বাচন করুন —",
    date: "তারিখ",
    time: "সময়",
    notes: "নোট (ঐচ্ছিক)",
    notesPlaceholder: "আপনার লক্ষণ বর্ণনা করুন...",
    bookingBtn: "📅 অ্যাপয়েন্টমেন্ট বুক করুন",
    booking: "বুকিং হচ্ছে…",
    availableDoctors: "উপলব্ধ ডাক্তার",
    noAppointmentsYet: "এখনও কোনো অ্যাপয়েন্টমেন্ট নেই।",
    logout: "লগআউট",
    language: "ভাষা",
    selectLanguage: "ভাষা নির্বাচন করুন",
    whatWeOffer: "আমরা কী অফার করি",
    bookNow: "এখনই বুক করুন →",
    contactUs: "যোগাযোগ করুন",
    sendMessage: "বার্তা পাঠান",
    joinMedicore: "আজই MediCore এ যোগ দিন",
    createPatientAccount: "রোগীর অ্যাকাউন্ট তৈরি করুন",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    registering: "নিবন্ধন হচ্ছে…",
    registrationFailed: "নিবন্ধন ব্যর্থ। আবার চেষ্টা করুন।",
  },

  te: {
    home: "హోమ్",
    services: "సేవలు",
    doctors: "డాక్టర్లు",
    about: "మా గురించి",
    contact: "సంప్రదించండి",
    login: "లాగిన్",
    registerFree: "ఉచితంగా నమోదు చేసుకోండి",
    myDashboard: "నా డాష్‌బోర్డ్ →",
    logout: "లాగ్అవుట్",
    tagline: "భారతదేశం యొక్క #1 ఆసుపత్రి నిర్వహణ వేదిక",
    heroTitle1: "మీ ఆరోగ్యం,",
    heroTitle2: "మా ప్రాధాన్యత",
    heroDesc:
      "అపాయింట్‌మెంట్‌లు బుక్ చేసుకోండి, అగ్రశ్రేణి వైద్యులను సంప్రదించండి.",
    bookAppointment: "అపాయింట్‌మెంట్ బుక్ చేయండి →",
    exploreServices: "సేవలు చూడండి",
    statDoctors: "డాక్టర్లు",
    statPatients: "రోగులు",
    statSatisfaction: "సంతృప్తి",
    signIn: "సైన్ ఇన్",
    signingIn: "సైన్ ఇన్ అవుతోంది…",
    patientLogin: "రోగి లాగిన్",
    accessYourAccount: "మీ ఖాతాను యాక్సెస్ చేయండి.",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    dontHaveAccount: "ఖాతా లేదా?",
    register: "నమోదు చేయండి",
    loginFailed: "లాగిన్ విఫలమైంది. మళ్ళీ ప్రయత్నించండి.",
    showPassword: "పాస్‌వర్డ్ చూపించు",
    hidePassword: "పాస్‌వర్డ్ దాచు",
    fullName: "పూర్తి పేరు",
    phone2: "ఫోన్",
    department: "విభాగం",
    selectDepartment: "— విభాగం ఎంచుకోండి —",
    specialization: "ప్రత్యేకత",
    consultationFee: "సంప్రదింపు రుసుము (₹)",
    pleaseWait: "దయచేసి వేచి ఉండండి…",
    bookAppointmentTab: "అపాయింట్‌మెంట్ బుక్ చేయండి",
    myAppointments: "నా అపాయింట్‌మెంట్‌లు",
    newAppointment: "కొత్త అపాయింట్‌మెంట్",
    selectDoctor: "డాక్టర్‌ని ఎంచుకోండి",
    chooseDoctor: "— డాక్టర్‌ని ఎంచుకోండి —",
    date: "తేదీ",
    time: "సమయం",
    notes: "గమనికలు (ఐచ్ఛికం)",
    notesPlaceholder: "మీ లక్షణాలను వివరించండి...",
    bookingBtn: "📅 అపాయింట్‌మెంట్ బుక్ చేయండి",
    booking: "బుకింగ్ అవుతోంది…",
    availableDoctors: "అందుబాటులో ఉన్న డాక్టర్లు",
    noAppointmentsYet: "ఇంకా అపాయింట్‌మెంట్‌లు లేవు.",
    language: "భాష",
    selectLanguage: "భాష ఎంచుకోండి",
    whatWeOffer: "మేము ఏమి అందిస్తున్నాము",
    bookNow: "ఇప్పుడే బుక్ చేయండి →",
    contactUs: "సంప్రదించండి",
    sendMessage: "సందేశం పంపండి",
    joinMedicore: "ఈ రోజే MediCore లో చేరండి",
    createPatientAccount: "రోగి ఖాతా సృష్టించండి",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    registering: "నమోదు అవుతోంది…",
    registrationFailed: "నమోదు విఫలమైంది. మళ్ళీ ప్రయత్నించండి.",
  },

  mr: {
    home: "होम",
    services: "सेवा",
    doctors: "डॉक्टर",
    about: "आमच्याबद्दल",
    contact: "संपर्क",
    login: "लॉगिन",
    registerFree: "मोफत नोंदणी",
    myDashboard: "माझा डॅशबोर्ड →",
    logout: "लॉगआउट",
    tagline: "भारताचे #1 रुग्णालय व्यवस्थापन व्यासपीठ",
    heroTitle1: "तुमचे आरोग्य,",
    heroTitle2: "आमची प्राथमिकता",
    heroDesc:
      "अपॉइंटमेंट बुक करा, शीर्ष डॉक्टरांशी सल्लामसलत करा — सर्व एकाच ठिकाणी.",
    bookAppointment: "अपॉइंटमेंट बुक करा →",
    exploreServices: "सेवा पहा",
    statDoctors: "डॉक्टर",
    statPatients: "रुग्ण",
    statSatisfaction: "समाधान",
    signIn: "साइन इन",
    signingIn: "साइन इन होत आहे…",
    patientLogin: "रुग्ण लॉगिन",
    accessYourAccount: "तुमचे खाते ऍक्सेस करा.",
    email: "ईमेल",
    password: "पासवर्ड",
    dontHaveAccount: "खाते नाही?",
    register: "नोंदणी करा",
    loginFailed: "लॉगिन अयशस्वी. पुन्हा प्रयत्न करा.",
    showPassword: "पासवर्ड दाखवा",
    hidePassword: "पासवर्ड लपवा",
    fullName: "पूर्ण नाव",
    phone2: "फोन",
    department: "विभाग",
    selectDepartment: "— विभाग निवडा —",
    specialization: "विशेषज्ञता",
    consultationFee: "सल्लामसलत शुल्क (₹)",
    pleaseWait: "कृपया प्रतीक्षा करा…",
    bookAppointmentTab: "अपॉइंटमेंट बुक करा",
    myAppointments: "माझ्या अपॉइंटमेंट",
    newAppointment: "नवीन अपॉइंटमेंट",
    selectDoctor: "डॉक्टर निवडा",
    chooseDoctor: "— डॉक्टर निवडा —",
    date: "तारीख",
    time: "वेळ",
    notes: "नोट्स (पर्यायी)",
    notesPlaceholder: "तुमची लक्षणे सांगा...",
    bookingBtn: "📅 अपॉइंटमेंट बुक करा",
    booking: "बुकिंग होत आहे…",
    availableDoctors: "उपलब्ध डॉक्टर",
    noAppointmentsYet: "अजून कोणत्याही अपॉइंटमेंट नाहीत.",
    language: "भाषा",
    selectLanguage: "भाषा निवडा",
    whatWeOffer: "आम्ही काय देतो",
    bookNow: "आता बुक करा →",
    contactUs: "संपर्क करा",
    sendMessage: "संदेश पाठवा",
    joinMedicore: "आज MediCore मध्ये सामील व्हा",
    createPatientAccount: "रुग्ण खाते तयार करा",
    alreadyHaveAccount: "आधीपासून खाते आहे?",
    registering: "नोंदणी होत आहे…",
    registrationFailed: "नोंदणी अयशस्वी. पुन्हा प्रयत्न करा.",
  },

  ta: {
    home: "முகப்பு",
    services: "சேவைகள்",
    doctors: "மருத்துவர்கள்",
    about: "எங்களைப் பற்றி",
    contact: "தொடர்பு",
    login: "உள்நுழை",
    registerFree: "இலவசமாக பதிவு செய்யுங்கள்",
    myDashboard: "என் டாஷ்போர்டு →",
    logout: "வெளியேறு",
    tagline: "இந்தியாவின் #1 மருத்துவமனை மேலாண்மை தளம்",
    heroTitle1: "உங்கள் ஆரோக்கியம்,",
    heroTitle2: "எங்கள் முன்னுரிமை",
    heroDesc:
      "சந்திப்புகளை பதிவு செய்யுங்கள், சிறந்த மருத்துவர்களை அணுகுங்கள்.",
    bookAppointment: "சந்திப்பு பதிவு செய்யுங்கள் →",
    exploreServices: "சேவைகளை காணுங்கள்",
    statDoctors: "மருத்துவர்கள்",
    statPatients: "நோயாளிகள்",
    statSatisfaction: "திருப்தி",
    signIn: "உள்நுழை",
    signingIn: "உள்நுழைகிறது…",
    patientLogin: "நோயாளி உள்நுழைவு",
    accessYourAccount: "உங்கள் கணக்கை அணுகுங்கள்.",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    dontHaveAccount: "கணக்கு இல்லையா?",
    register: "பதிவு செய்யுங்கள்",
    loginFailed: "உள்நுழைவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.",
    showPassword: "கடவுச்சொல்லை காட்டு",
    hidePassword: "கடவுச்சொல்லை மறை",
    fullName: "முழு பெயர்",
    phone2: "தொலைபேசி",
    department: "துறை",
    selectDepartment: "— துறையை தேர்ந்தெடுக்கவும் —",
    specialization: "நிபுணத்துவம்",
    consultationFee: "ஆலோசனை கட்டணம் (₹)",
    pleaseWait: "தயவுசெய்து காத்திருக்கவும்…",
    bookAppointmentTab: "சந்திப்பு பதிவு",
    myAppointments: "என் சந்திப்புகள்",
    newAppointment: "புதிய சந்திப்பு",
    selectDoctor: "மருத்துவரை தேர்ந்தெடுக்கவும்",
    chooseDoctor: "— மருத்துவரை தேர்ந்தெடுக்கவும் —",
    date: "தேதி",
    time: "நேரம்",
    notes: "குறிப்புகள் (விருப்பம்)",
    notesPlaceholder: "உங்கள் அறிகுறிகளை விவரிக்கவும்...",
    bookingBtn: "📅 சந்திப்பு பதிவு",
    booking: "பதிவு ஆகிறது…",
    availableDoctors: "கிடைக்கும் மருத்துவர்கள்",
    noAppointmentsYet: "இன்னும் சந்திப்புகள் இல்லை.",
    language: "மொழி",
    selectLanguage: "மொழியை தேர்ந்தெடுக்கவும்",
    whatWeOffer: "நாங்கள் என்ன வழங்குகிறோம்",
    bookNow: "இப்போதே பதிவு →",
    contactUs: "தொடர்பு கொள்ளுங்கள்",
    sendMessage: "செய்தி அனுப்பு",
    joinMedicore: "இன்று MediCore இல் சேருங்கள்",
    createPatientAccount: "நோயாளி கணக்கு உருவாக்கு",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    registering: "பதிவு ஆகிறது…",
    registrationFailed: "பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.",
  },

  gu: {
    home: "હોમ",
    services: "સેવાઓ",
    doctors: "ડૉક્ટર",
    about: "અમારા વિશે",
    contact: "સંપર્ક",
    login: "લૉગિન",
    registerFree: "મફત નોંધણી",
    myDashboard: "મારું ડૅશબોર્ડ →",
    logout: "લૉગઆઉટ",
    tagline: "ભારતનું #1 હૉસ્પિટલ મૅનેજમૅન્ટ પ્લૅટફૉર્મ",
    heroTitle1: "તમારી તંદુરસ્તી,",
    heroTitle2: "અમારી પ્રાથમિકતા",
    heroDesc: "અૅપૉઇન્ટમૅન્ટ બુક કરો, ટૉચના ડૉક્ટરોની સલાહ લો.",
    bookAppointment: "અૅપૉઇન્ટમૅન્ટ બુક કરો →",
    exploreServices: "સેવાઓ જુઓ",
    statDoctors: "ડૉક્ટર",
    statPatients: "દર્દી",
    statSatisfaction: "સંતોષ",
    signIn: "સાઇન ઇન",
    signingIn: "સાઇન ઇન થઈ રહ્યું છે…",
    patientLogin: "દર્દી લૉગિન",
    accessYourAccount: "તમારું ઍકાઉન્ટ ઍક્સેસ કરો.",
    email: "ઇમૅઇલ",
    password: "પાસવર્ડ",
    dontHaveAccount: "ઍકાઉન્ટ નથી?",
    register: "નોંધણી કરો",
    loginFailed: "લૉગિન નિષ્ફળ. ફરી પ્રયાસ કરો.",
    showPassword: "પાસવર્ડ બતાવો",
    hidePassword: "પાસવર્ડ છુપાવો",
    fullName: "પૂરું નામ",
    phone2: "ફોન",
    department: "વિભાગ",
    selectDepartment: "— વિભાગ પસંદ કરો —",
    specialization: "વિશેષતા",
    consultationFee: "પરામર્શ ફી (₹)",
    pleaseWait: "કૃપા કરી રાહ જુઓ…",
    bookAppointmentTab: "અૅપૉઇન્ટમૅન્ટ બુક કરો",
    myAppointments: "મારી અૅપૉઇન્ટમૅન્ટ",
    newAppointment: "નવી અૅપૉઇન્ટમૅન્ટ",
    selectDoctor: "ડૉક્ટર પસંદ કરો",
    chooseDoctor: "— ડૉક્ટર પસંદ કરો —",
    date: "તારીખ",
    time: "સમય",
    notes: "નોંધ (વૈકલ્પિક)",
    notesPlaceholder: "તમારાં લક્ષણો જણાવો...",
    bookingBtn: "📅 અૅપૉઇન્ટમૅન્ટ બુક કરો",
    booking: "બુકિંગ થઈ રહ્યું છે…",
    availableDoctors: "ઉપલબ્ધ ડૉક્ટર",
    noAppointmentsYet: "હજુ કોઈ અૅપૉઇન્ટમૅન્ટ નથી.",
    language: "ભાષા",
    selectLanguage: "ભાષા પસંદ કરો",
    whatWeOffer: "અમે શું ઓફર કરીએ છીએ",
    bookNow: "હમણાં બુક કરો →",
    contactUs: "સંપર્ક કરો",
    sendMessage: "સંદેશ મોકલો",
    joinMedicore: "આજે MediCore સાથે જોડાઓ",
    createPatientAccount: "દર્દી ઍકાઉન્ટ બનાવો",
    alreadyHaveAccount: "પહેલેથી ઍકાઉન્ટ છે?",
    registering: "નોંધણી થઈ રહી છે…",
    registrationFailed: "નોંધણી નિષ્ફળ. ફરી પ્રયાસ કરો.",
  },

  kn: {
    home: "ಮುಖಪುಟ",
    services: "ಸೇವೆಗಳು",
    doctors: "ವೈದ್ಯರು",
    about: "ನಮ್ಮ ಬಗ್ಗೆ",
    contact: "ಸಂಪರ್ಕ",
    login: "ಲಾಗಿನ್",
    registerFree: "ಉಚಿತ ನೋಂದಣಿ",
    myDashboard: "ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ →",
    logout: "ಲಾಗ್ಔಟ್",
    tagline: "ಭಾರತದ #1 ಆಸ್ಪತ್ರೆ ನಿರ್ವಹಣಾ ವೇದಿಕೆ",
    heroTitle1: "ನಿಮ್ಮ ಆರೋಗ್ಯ,",
    heroTitle2: "ನಮ್ಮ ಆದ್ಯತೆ",
    heroDesc: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ, ಅಗ್ರ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    bookAppointment: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ →",
    exploreServices: "ಸೇವೆಗಳನ್ನು ನೋಡಿ",
    statDoctors: "ವೈದ್ಯರು",
    statPatients: "ರೋಗಿಗಳು",
    statSatisfaction: "ತೃಪ್ತಿ",
    signIn: "ಸೈನ್ ಇನ್",
    signingIn: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ…",
    patientLogin: "ರೋಗಿ ಲಾಗಿನ್",
    accessYourAccount: "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಪ್ರವೇಶಿಸಿ.",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    dontHaveAccount: "ಖಾತೆ ಇಲ್ಲವೇ?",
    register: "ನೋಂದಣಿ ಮಾಡಿ",
    loginFailed: "ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    showPassword: "ಪಾಸ್‌ವರ್ಡ್ ತೋರಿಸಿ",
    hidePassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆಮಾಡಿ",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    phone2: "ಫೋನ್",
    department: "ವಿಭಾಗ",
    selectDepartment: "— ವಿಭಾಗ ಆರಿಸಿ —",
    specialization: "ವಿಶೇಷತೆ",
    consultationFee: "ಸಮಾಲೋಚನಾ ಶುಲ್ಕ (₹)",
    pleaseWait: "ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ…",
    bookAppointmentTab: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ",
    myAppointments: "ನನ್ನ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು",
    newAppointment: "ಹೊಸ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್",
    selectDoctor: "ವೈದ್ಯರನ್ನು ಆರಿಸಿ",
    chooseDoctor: "— ವೈದ್ಯರನ್ನು ಆರಿಸಿ —",
    date: "ದಿನಾಂಕ",
    time: "ಸಮಯ",
    notes: "ಟಿಪ್ಪಣಿಗಳು (ಐಚ್ಛಿಕ)",
    notesPlaceholder: "ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ...",
    bookingBtn: "📅 ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ",
    booking: "ಬುಕ್ ಆಗುತ್ತಿದೆ…",
    availableDoctors: "ಲಭ್ಯವಿರುವ ವೈದ್ಯರು",
    noAppointmentsYet: "ಇನ್ನೂ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳಿಲ್ಲ.",
    language: "ಭಾಷೆ",
    selectLanguage: "ಭಾಷೆ ಆರಿಸಿ",
    whatWeOffer: "ನಾವು ಏನನ್ನು ನೀಡುತ್ತೇವೆ",
    bookNow: "ಈಗಲೇ ಬುಕ್ →",
    contactUs: "ಸಂಪರ್ಕಿಸಿ",
    sendMessage: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    joinMedicore: "ಇಂದೇ MediCore ಗೆ ಸೇರಿ",
    createPatientAccount: "ರೋಗಿ ಖಾತೆ ರಚಿಸಿ",
    alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    registering: "ನೋಂದಣಿ ಆಗುತ್ತಿದೆ…",
    registrationFailed: "ನೋಂದಣಿ ವಿಫಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  },

  ml: {
    home: "ഹോം",
    services: "സേവനങ്ങൾ",
    doctors: "ഡോക്ടർമാർ",
    about: "ഞങ്ങളെക്കുറിച്ച്",
    contact: "ബന്ധപ്പെടുക",
    login: "ലോഗിൻ",
    registerFree: "സൗജന്യ രജിസ്ട്രേഷൻ",
    myDashboard: "എന്റെ ഡാഷ്‌ബോർഡ് →",
    logout: "ലോഗ്ഔട്ട്",
    tagline: "ഇന്ത്യയിലെ #1 ആശുപത്രി മാനേജ്‌മെന്റ് പ്ലാറ്റ്‌ഫോം",
    heroTitle1: "നിങ്ങളുടെ ആരോഗ്യം,",
    heroTitle2: "ഞങ്ങളുടെ മുൻഗണന",
    heroDesc:
      "അപ്പോയിന്റ്‌മെന്റ് ബുക്ക് ചെയ്യൂ, മികച്ച ഡോക്ടർമാരെ കൺസൾട്ട് ചെയ്യൂ.",
    bookAppointment: "അപ്പോയിന്റ്‌മെന്റ് ബുക്ക് ചെയ്യൂ →",
    exploreServices: "സേവനങ്ങൾ കാണൂ",
    statDoctors: "ഡോക്ടർമാർ",
    statPatients: "രോഗികൾ",
    statSatisfaction: "സംതൃപ്തി",
    signIn: "സൈൻ ഇൻ",
    signingIn: "സൈൻ ഇൻ ആകുന്നു…",
    patientLogin: "രോഗി ലോഗിൻ",
    accessYourAccount: "നിങ്ങളുടെ അക്കൗണ്ട് ആക്‌സസ് ചെയ്യൂ.",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    dontHaveAccount: "അക്കൗണ്ട് ഇല്ലേ?",
    register: "രജിസ്റ്റർ ചെയ്യൂ",
    loginFailed: "ലോഗിൻ പരാജയപ്പെട്ടു. വീണ്ടും ശ്രമിക്കൂ.",
    showPassword: "പാസ്‌വേഡ് കാണിക്കൂ",
    hidePassword: "പാസ്‌വേഡ് മറയ്ക്കൂ",
    fullName: "മുഴുവൻ പേര്",
    phone2: "ഫോൺ",
    department: "വിഭാഗം",
    selectDepartment: "— വിഭാഗം തിരഞ്ഞെടുക്കൂ —",
    specialization: "സ്‌പെഷ്യലൈസേഷൻ",
    consultationFee: "കൺസൾട്ടേഷൻ ഫീ (₹)",
    pleaseWait: "ദയവായി കാത്തിരിക്കൂ…",
    bookAppointmentTab: "അപ്പോയിന്റ്‌മെന്റ് ബുക്ക്",
    myAppointments: "എന്റെ അപ്പോയിന്റ്‌മെന്റുകൾ",
    newAppointment: "പുതിയ അപ്പോയിന്റ്‌മെന്റ്",
    selectDoctor: "ഡോക്ടറെ തിരഞ്ഞെടുക്കൂ",
    chooseDoctor: "— ഡോക്ടറെ തിരഞ്ഞെടുക്കൂ —",
    date: "തീയതി",
    time: "സമയം",
    notes: "കുറിപ്പുകൾ (ഐഛിക)",
    notesPlaceholder: "നിങ്ങളുടെ ലക്ഷണങ്ങൾ വിവരിക്കൂ...",
    bookingBtn: "📅 അപ്പോയിന്റ്‌മെന്റ് ബുക്ക്",
    booking: "ബുക്ക് ആകുന്നു…",
    availableDoctors: "ലഭ്യമായ ഡോക്ടർമാർ",
    noAppointmentsYet: "ഇനിയും അപ്പോയിന്റ്‌മെന്റുകൾ ഇല്ല.",
    language: "ഭാഷ",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കൂ",
    whatWeOffer: "ഞങ്ങൾ എന്ത് വാഗ്ദാനം ചെയ്യുന്നു",
    bookNow: "ഇപ്പോൾ ബുക്ക് →",
    contactUs: "ബന്ധപ്പെടൂ",
    sendMessage: "സന്ദേശം അയക്കൂ",
    joinMedicore: "ഇന്ന് MediCore ൽ ചേരൂ",
    createPatientAccount: "രോഗി അക്കൗണ്ട് ഉണ്ടാക്കൂ",
    alreadyHaveAccount: "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?",
    registering: "രജിസ്റ്റർ ആകുന്നു…",
    registrationFailed: "രജിസ്ട്രേഷൻ പരാജയപ്പെട്ടു. വീണ്ടും ശ്രമിക്കൂ.",
  },

  pa: {
    home: "ਹੋਮ",
    services: "ਸੇਵਾਵਾਂ",
    doctors: "ਡਾਕਟਰ",
    about: "ਸਾਡੇ ਬਾਰੇ",
    contact: "ਸੰਪਰਕ",
    login: "ਲੌਗਇਨ",
    registerFree: "ਮੁਫ਼ਤ ਰਜਿਸਟਰ ਕਰੋ",
    myDashboard: "ਮੇਰਾ ਡੈਸ਼ਬੋਰਡ →",
    logout: "ਲੌਗਆਉਟ",
    tagline: "ਭਾਰਤ ਦਾ #1 ਹਸਪਤਾਲ ਪ੍ਰਬੰਧਨ ਪਲੇਟਫਾਰਮ",
    heroTitle1: "ਤੁਹਾਡੀ ਸਿਹਤ,",
    heroTitle2: "ਸਾਡੀ ਤਰਜੀਹ",
    heroDesc: "ਅਪੌਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ, ਚੋਟੀ ਦੇ ਡਾਕਟਰਾਂ ਨਾਲ ਸਲਾਹ ਕਰੋ।",
    bookAppointment: "ਅਪੌਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ →",
    exploreServices: "ਸੇਵਾਵਾਂ ਦੇਖੋ",
    statDoctors: "ਡਾਕਟਰ",
    statPatients: "ਮਰੀਜ਼",
    statSatisfaction: "ਸੰਤੁਸ਼ਟੀ",
    signIn: "ਸਾਈਨ ਇਨ",
    signingIn: "ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ…",
    patientLogin: "ਮਰੀਜ਼ ਲੌਗਇਨ",
    accessYourAccount: "ਆਪਣਾ ਖਾਤਾ ਐਕਸੈਸ ਕਰੋ।",
    email: "ਈਮੇਲ",
    password: "ਪਾਸਵਰਡ",
    dontHaveAccount: "ਖਾਤਾ ਨਹੀਂ ਹੈ?",
    register: "ਰਜਿਸਟਰ ਕਰੋ",
    loginFailed: "ਲੌਗਇਨ ਅਸਫਲ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    showPassword: "ਪਾਸਵਰਡ ਦਿਖਾਓ",
    hidePassword: "ਪਾਸਵਰਡ ਲੁਕਾਓ",
    fullName: "ਪੂਰਾ ਨਾਮ",
    phone2: "ਫ਼ੋਨ",
    department: "ਵਿਭਾਗ",
    selectDepartment: "— ਵਿਭਾਗ ਚੁਣੋ —",
    specialization: "ਵਿਸ਼ੇਸ਼ਤਾ",
    consultationFee: "ਸਲਾਹ ਫੀਸ (₹)",
    pleaseWait: "ਕਿਰਪਾ ਉਡੀਕ ਕਰੋ…",
    bookAppointmentTab: "ਅਪੌਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ",
    myAppointments: "ਮੇਰੀਆਂ ਅਪੌਇੰਟਮੈਂਟਾਂ",
    newAppointment: "ਨਵੀਂ ਅਪੌਇੰਟਮੈਂਟ",
    selectDoctor: "ਡਾਕਟਰ ਚੁਣੋ",
    chooseDoctor: "— ਡਾਕਟਰ ਚੁਣੋ —",
    date: "ਮਿਤੀ",
    time: "ਸਮਾਂ",
    notes: "ਨੋਟਸ (ਵਿਕਲਪਿਕ)",
    notesPlaceholder: "ਆਪਣੇ ਲੱਛਣ ਦੱਸੋ...",
    bookingBtn: "📅 ਅਪੌਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ",
    booking: "ਬੁਕਿੰਗ ਹੋ ਰਹੀ ਹੈ…",
    availableDoctors: "ਉਪਲਬਧ ਡਾਕਟਰ",
    noAppointmentsYet: "ਅਜੇ ਕੋਈ ਅਪੌਇੰਟਮੈਂਟ ਨਹੀਂ।",
    language: "ਭਾਸ਼ਾ",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    whatWeOffer: "ਅਸੀਂ ਕੀ ਪੇਸ਼ ਕਰਦੇ ਹਾਂ",
    bookNow: "ਹੁਣੇ ਬੁੱਕ ਕਰੋ →",
    contactUs: "ਸੰਪਰਕ ਕਰੋ",
    sendMessage: "ਸੁਨੇਹਾ ਭੇਜੋ",
    joinMedicore: "ਅੱਜ MediCore ਨਾਲ ਜੁੜੋ",
    createPatientAccount: "ਮਰੀਜ਼ ਖਾਤਾ ਬਣਾਓ",
    alreadyHaveAccount: "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?",
    registering: "ਰਜਿਸਟਰ ਹੋ ਰਿਹਾ ਹੈ…",
    registrationFailed: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਸਫਲ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
  },

  or: {
    home: "ହୋମ",
    services: "ସେବାସମୂହ",
    doctors: "ଡାକ୍ତର",
    about: "ଆମ ବିଷୟରେ",
    contact: "ଯୋଗାଯୋଗ",
    login: "ଲଗଇନ",
    registerFree: "ମାଗଣା ପଞ୍ଜୀକରଣ",
    myDashboard: "ମୋ ଡ୍ୟାଶବୋର୍ଡ →",
    logout: "ଲଗଆଉଟ",
    tagline: "ଭାରତର #1 ଡାକ୍ତରଖାନା ପରିଚାଳନା ପ୍ଲାଟଫର୍ମ",
    heroTitle1: "ଆପଣଙ୍କ ସ୍ୱାସ୍ଥ୍ୟ,",
    heroTitle2: "ଆମର ପ୍ରାଥମିକତା",
    heroDesc:
      "ଅ୍ୟାପଏଣ୍ଟମେଣ୍ଟ ବୁକ୍ କରନ୍ତୁ, ଶ୍ରେଷ୍ଠ ଡାକ୍ତରଙ୍କ ସହ ପରାମର୍ଶ ନିଅନ୍ତୁ।",
    bookAppointment: "ଅ୍ୟାପଏଣ୍ଟମେଣ୍ଟ ବୁକ୍ →",
    exploreServices: "ସେବା ଦେଖନ୍ତୁ",
    statDoctors: "ଡାକ୍ତର",
    statPatients: "ରୋଗୀ",
    statSatisfaction: "ସନ୍ତୁଷ୍ଟି",
    signIn: "ସାଇନ ଇନ",
    signingIn: "ସାଇନ ଇନ ହେଉଛି…",
    patientLogin: "ରୋଗୀ ଲଗଇନ",
    accessYourAccount: "ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ଆକ୍ସେସ କରନ୍ତୁ।",
    email: "ଇମେଲ",
    password: "ପାସୱାର୍ଡ",
    dontHaveAccount: "ଆକାଉଣ୍ଟ ନାହିଁ?",
    register: "ପଞ୍ଜୀକରଣ କରନ୍ତୁ",
    loginFailed: "ଲଗଇନ ବିଫଳ। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
    showPassword: "ପାସୱାର୍ଡ ଦେଖାନ୍ତୁ",
    hidePassword: "ପାସୱାର୍ଡ ଲୁଚାନ୍ତୁ",
    fullName: "ପୂର୍ଣ ନାମ",
    phone2: "ଫୋନ",
    department: "ବିଭାଗ",
    selectDepartment: "— ବିଭାଗ ବାଛନ୍ତୁ —",
    specialization: "ବିଶେଷଜ୍ଞତା",
    consultationFee: "ପରାମର୍ଶ ଶୁଳ୍କ (₹)",
    pleaseWait: "ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ…",
    bookAppointmentTab: "ଅ୍ୟାପଏଣ୍ଟମେଣ୍ଟ ବୁକ",
    myAppointments: "ମୋ ଅ୍ୟାପଏଣ୍ଟମେଣ୍ଟ",
    newAppointment: "ନୂତନ ଅ୍ୟାପଏଣ୍ଟମେଣ୍ଟ",
    selectDoctor: "ଡାକ୍ତର ବାଛନ୍ତୁ",
    chooseDoctor: "— ଡାକ୍ତର ବାଛନ୍ତୁ —",
    date: "ତାରିଖ",
    time: "ସମୟ",
    notes: "ଟୀକା (ଐଚ୍ଛିକ)",
    notesPlaceholder: "ଆପଣଙ୍କ ଲକ୍ଷଣ ବର୍ଣ୍ଣନା କରନ୍ତୁ...",
    bookingBtn: "📅 ଅ୍ୟାପଏଣ୍ଟମେଣ୍ଟ ବୁକ",
    booking: "ବୁକ ହେଉଛି…",
    availableDoctors: "ଉପଲବ୍ଧ ଡାକ୍ତର",
    noAppointmentsYet: "ଆଜି ପର୍ଯ୍ୟନ୍ତ କୌଣସି ଅ୍ୟାପଏଣ୍ଟମେଣ୍ଟ ନାହିଁ।",
    language: "ଭାଷା",
    selectLanguage: "ଭାଷା ବାଛନ୍ତୁ",
    whatWeOffer: "ଆମେ କ'ଣ ପ୍ରଦାନ କରୁ",
    bookNow: "ବର୍ତ୍ତମାନ ବୁକ →",
    contactUs: "ଯୋଗାଯୋଗ କରନ୍ତୁ",
    sendMessage: "ବାର୍ତ୍ତା ପଠାନ୍ତୁ",
    joinMedicore: "ଆଜି MediCore ସହ ଯୋଗ ଦିଅ",
    createPatientAccount: "ରୋଗୀ ଆକାଉଣ୍ଟ ତିଆରି",
    alreadyHaveAccount: "ଈ ପୂର୍ବ ଆକାଉଣ୍ଟ ଅଛି?",
    registering: "ପଞ୍ଜୀକରଣ ହେଉଛି…",
    registrationFailed: "ପଞ୍ଜୀକରଣ ବିଫଳ। ପୁଣି ଚେଷ୍ଟା।",
  },

  as: {
    home: "হোম",
    services: "সেৱাসমূহ",
    doctors: "চিকিৎসক",
    about: "আমাৰ বিষয়ে",
    contact: "যোগাযোগ",
    login: "লগইন",
    registerFree: "বিনামূলীয়া পঞ্জীয়ন",
    myDashboard: "মোৰ ডেশ্বব'ৰ্ড →",
    logout: "লগআউট",
    tagline: "ভাৰতৰ #1 হাস্পতাল পৰিচালনা প্লেটফৰ্ম",
    heroTitle1: "আপোনাৰ স্বাস্থ্য,",
    heroTitle2: "আমাৰ অগ্ৰাধিকাৰ",
    heroDesc: "এপইণ্টমেণ্ট বুক কৰক, শীৰ্ষ চিকিৎসকৰ সৈতে পৰামৰ্শ কৰক।",
    bookAppointment: "এপইণ্টমেণ্ট বুক কৰক →",
    exploreServices: "সেৱাসমূহ চাওক",
    statDoctors: "চিকিৎসক",
    statPatients: "ৰোগী",
    statSatisfaction: "সন্তুষ্টি",
    signIn: "চাইন ইন",
    signingIn: "চাইন ইন হৈছে…",
    patientLogin: "ৰোগী লগইন",
    accessYourAccount: "আপোনাৰ একাউণ্ট এক্সেছ কৰক।",
    email: "ইমেইল",
    password: "পাছৱৰ্ড",
    dontHaveAccount: "একাউণ্ট নাই?",
    register: "পঞ্জীয়ন কৰক",
    loginFailed: "লগইন বিফল। পুনৰ চেষ্টা কৰক।",
    showPassword: "পাছৱৰ্ড দেখুৱাওক",
    hidePassword: "পাছৱৰ্ড লুকাওক",
    fullName: "সম্পূৰ্ণ নাম",
    phone2: "ফোন",
    department: "বিভাগ",
    selectDepartment: "— বিভাগ বাছক —",
    specialization: "বিশেষজ্ঞতা",
    consultationFee: "পৰামৰ্শ মাচুল (₹)",
    pleaseWait: "অনুগ্ৰহ কৰি অপেক্ষা কৰক…",
    bookAppointmentTab: "এপইণ্টমেণ্ট বুক",
    myAppointments: "মোৰ এপইণ্টমেণ্টসমূহ",
    newAppointment: "নতুন এপইণ্টমেণ্ট",
    selectDoctor: "চিকিৎসক বাছক",
    chooseDoctor: "— চিকিৎসক বাছক —",
    date: "তাৰিখ",
    time: "সময়",
    notes: "টোকাসমূহ (বৈকল্পিক)",
    notesPlaceholder: "আপোনাৰ লক্ষণসমূহ বৰ্ণনা কৰক...",
    bookingBtn: "📅 এপইণ্টমেণ্ট বুক",
    booking: "বুক হৈছে…",
    availableDoctors: "উপলব্ধ চিকিৎসক",
    noAppointmentsYet: "এতিয়ালৈ কোনো এপইণ্টমেণ্ট নাই।",
    language: "ভাষা",
    selectLanguage: "ভাষা বাছক",
    whatWeOffer: "আমি কি প্ৰদান কৰো",
    bookNow: "এতিয়াই বুক →",
    contactUs: "যোগাযোগ কৰক",
    sendMessage: "বাৰ্তা পঠিয়াওক",
    joinMedicore: "আজি MediCore ত যোগ দিয়ক",
    createPatientAccount: "ৰোগী একাউণ্ট বনাওক",
    alreadyHaveAccount: "আগতীয়াকৈ একাউণ্ট আছে?",
    registering: "পঞ্জীয়ন হৈছে…",
    registrationFailed: "পঞ্জীয়ন বিফল। পুনৰ চেষ্টা।",
  },

  ur: {
    home: "ہوم",
    services: "خدمات",
    doctors: "ڈاکٹر",
    about: "ہمارے بارے میں",
    contact: "رابطہ",
    login: "لاگ ان",
    registerFree: "مفت رجسٹریشن",
    myDashboard: "میرا ڈیش بورڈ ←",
    logout: "لاگ آؤٹ",
    tagline: "ہندوستان کا #1 ہسپتال مینجمنٹ پلیٹ فارم",
    heroTitle1: "آپ کی صحت،",
    heroTitle2: "ہماری ترجیح",
    heroDesc: "اپائنٹمنٹ بک کریں، ٹاپ ڈاکٹروں سے مشورہ کریں۔",
    bookAppointment: "اپائنٹمنٹ بک کریں ←",
    exploreServices: "خدمات دیکھیں",
    statDoctors: "ڈاکٹر",
    statPatients: "مریض",
    statSatisfaction: "اطمینان",
    signIn: "سائن ان",
    signingIn: "سائن ان ہو رہا ہے…",
    patientLogin: "مریض لاگ ان",
    accessYourAccount: "اپنا اکاؤنٹ ایکسیس کریں۔",
    email: "ای میل",
    password: "پاس ورڈ",
    dontHaveAccount: "اکاؤنٹ نہیں ہے؟",
    register: "رجسٹر کریں",
    loginFailed: "لاگ ان ناکام۔ دوبارہ کوشش کریں۔",
    showPassword: "پاس ورڈ دکھائیں",
    hidePassword: "پاس ورڈ چھپائیں",
    fullName: "پورا نام",
    phone2: "فون",
    department: "شعبہ",
    selectDepartment: "— شعبہ منتخب کریں —",
    specialization: "تخصص",
    consultationFee: "مشاورتی فیس (₹)",
    pleaseWait: "براہ کرم انتظار کریں…",
    bookAppointmentTab: "اپائنٹمنٹ بک کریں",
    myAppointments: "میری اپائنٹمنٹ",
    newAppointment: "نئی اپائنٹمنٹ",
    selectDoctor: "ڈاکٹر منتخب کریں",
    chooseDoctor: "— ڈاکٹر منتخب کریں —",
    date: "تاریخ",
    time: "وقت",
    notes: "نوٹس (اختیاری)",
    notesPlaceholder: "اپنی علامات بیان کریں...",
    bookingBtn: "📅 اپائنٹمنٹ بک کریں",
    booking: "بکنگ ہو رہی ہے…",
    availableDoctors: "دستیاب ڈاکٹر",
    noAppointmentsYet: "ابھی تک کوئی اپائنٹمنٹ نہیں۔",
    language: "زبان",
    selectLanguage: "زبان منتخب کریں",
    whatWeOffer: "ہم کیا پیش کرتے ہیں",
    bookNow: "ابھی بک کریں ←",
    contactUs: "رابطہ کریں",
    sendMessage: "پیغام بھیجیں",
    joinMedicore: "آج MediCore سے جڑیں",
    createPatientAccount: "مریض اکاؤنٹ بنائیں",
    alreadyHaveAccount: "پہلے سے اکاؤنٹ ہے؟",
    registering: "رجسٹر ہو رہا ہے…",
    registrationFailed: "رجسٹریشن ناکام۔ دوبارہ کوشش کریں۔",
  },

  sa: {
    home: "गृहम्",
    services: "सेवाः",
    doctors: "चिकित्सकाः",
    about: "अस्माकं विषये",
    contact: "सम्पर्कः",
    login: "प्रवेशः",
    registerFree: "निःशुल्कं पञ्जीकरणम्",
    myDashboard: "मम डैशबोर्ड →",
    logout: "निर्गमनम्",
    tagline: "भारतस्य #1 चिकित्सालय प्रबन्धन मञ्चः",
    heroTitle1: "भवतः स्वास्थ्यम्,",
    heroTitle2: "अस्माकं प्राथमिकता",
    heroDesc: "नियुक्तिं बुक कुरुत, श्रेष्ठ चिकित्सकैः परामर्शं गृह्णीत।",
    bookAppointment: "नियुक्तिं बुक कुरुत →",
    exploreServices: "सेवाः पश्यत",
    statDoctors: "चिकित्सकाः",
    statPatients: "रोगिणः",
    statSatisfaction: "सन्तोषः",
    signIn: "प्रवेशः",
    signingIn: "प्रवेशः भवति…",
    patientLogin: "रोगी प्रवेशः",
    accessYourAccount: "भवतः खातं प्रविशत।",
    email: "विद्युत्पत्रम्",
    password: "गुप्तशब्दः",
    dontHaveAccount: "खातं नास्ति?",
    register: "पञ्जीकरणम् कुरुत",
    loginFailed: "प्रवेशः असफलः। पुनः प्रयतध्वम्।",
    showPassword: "गुप्तशब्दं दर्शयत",
    hidePassword: "गुप्तशब्दं गोपयत",
    fullName: "पूर्णं नाम",
    phone2: "दूरभाषः",
    department: "विभागः",
    selectDepartment: "— विभागं चिनुत —",
    specialization: "विशेषज्ञता",
    consultationFee: "परामर्श शुल्कम् (₹)",
    pleaseWait: "कृपया प्रतीक्षत…",
    bookAppointmentTab: "नियुक्तिं बुक कुरुत",
    myAppointments: "मम नियुक्तयः",
    newAppointment: "नूतना नियुक्तिः",
    selectDoctor: "चिकित्सकं चिनुत",
    chooseDoctor: "— चिकित्सकं चिनुत —",
    date: "दिनाङ्कः",
    time: "समयः",
    notes: "टिप्पण्यः (ऐच्छिकम्)",
    notesPlaceholder: "भवतः लक्षणानि वर्णयत...",
    bookingBtn: "📅 नियुक्तिं बुक कुरुत",
    booking: "बुकिंग भवति…",
    availableDoctors: "उपलब्धाः चिकित्सकाः",
    noAppointmentsYet: "अद्यावधि नियुक्तयः न सन्ति।",
    language: "भाषा",
    selectLanguage: "भाषां चिनुत",
    whatWeOffer: "वयं किं ददामः",
    bookNow: "अधुना बुक →",
    contactUs: "सम्पर्कं कुरुत",
    sendMessage: "सन्देशं प्रेषयत",
    joinMedicore: "अद्य MediCore सह योजयत",
    createPatientAccount: "रोगी खातं निर्मात",
    alreadyHaveAccount: "खातं पूर्वमेव अस्ति?",
    registering: "पञ्जीकरणं भवति…",
    registrationFailed: "पञ्जीकरणम् असफलम्। पुनः प्रयतध्वम्।",
  },
};

// ── Context ───────────────────────────────────────────────────────────────────
const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(
    () => localStorage.getItem("medicore_lang") || "en",
  );

  const switchLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem("medicore_lang", newLang);
  };

  const t = (key) =>
    translations[lang]?.[key] || translations["en"][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

// ── Dropdown Language Switcher ─────────────────────────────────────────────────
// Ek baar click → teeno pages pe apply hoga (localStorage se)
export function LanguageSwitcher({ style = {} }) {
  const { lang, switchLanguage } = useLanguage();
  const [open, setOpen] = useState(false);
  const ref = useRef(null);

  // Bahar click karne pe dropdown band ho
  useEffect(() => {
    const handler = (e) => {
      if (ref.current && !ref.current.contains(e.target)) setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  const current = LANGUAGES.find((l) => l.code === lang) || LANGUAGES[0];
  // RTL languages
  const isRTL = lang === "ur";

  return (
    <div
      ref={ref}
      style={{ position: "relative", display: "inline-block", ...style }}
    >
      {/* Trigger Button */}
      <button
        onClick={() => setOpen(!open)}
        style={{
          display: "flex",
          alignItems: "center",
          gap: 8,
          padding: "8px 14px",
          borderRadius: 10,
          border: "1.5px solid #e2e8f0",
          background: "#fff",
          color: "#0f172a",
          fontSize: 14,
          fontWeight: 600,
          cursor: "pointer",
          boxShadow: "0 1px 4px rgba(0,0,0,0.07)",
          transition: "all 0.2s",
          whiteSpace: "nowrap",
        }}
        title="Change Language"
      >
        🌐
        <span
          style={{ maxWidth: 90, overflow: "hidden", textOverflow: "ellipsis" }}
        >
          {current.native}
        </span>
        <span
          style={{
            fontSize: 10,
            color: "#94a3b8",
            transition: "transform 0.2s",
            transform: open ? "rotate(180deg)" : "rotate(0deg)",
            display: "inline-block",
          }}
        >
          ▼
        </span>
      </button>

      {/* Dropdown */}
      {open && (
        <div
          style={{
            position: "absolute",
            top: "calc(100% + 8px)",
            right: 0,
            background: "#fff",
            border: "1.5px solid #e2e8f0",
            borderRadius: 14,
            boxShadow: "0 8px 32px rgba(0,0,0,0.13)",
            zIndex: 9999,
            minWidth: 200,
            maxHeight: 380,
            overflowY: "auto",
            padding: "6px 0",
            animation: "fadeIn 0.15s ease",
          }}
        >
          <style>{`
            @keyframes fadeIn { from { opacity: 0; transform: translateY(-6px); } to { opacity: 1; transform: translateY(0); } }
            .lang-option:hover { background: #f0f9ff !important; }
          `}</style>
          {LANGUAGES.map((language) => (
            <button
              key={language.code}
              className="lang-option"
              onClick={() => {
                switchLanguage(language.code);
                setOpen(false);
              }}
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                width: "100%",
                padding: "10px 16px",
                border: "none",
                background: lang === language.code ? "#f0f9ff" : "transparent",
                cursor: "pointer",
                textAlign: "left",
                borderLeft:
                  lang === language.code
                    ? "3px solid #0ea5e9"
                    : "3px solid transparent",
                transition: "background 0.15s",
              }}
            >
              <div>
                <div
                  style={{
                    fontSize: 14,
                    fontWeight: lang === language.code ? 700 : 500,
                    color: lang === language.code ? "#0369a1" : "#0f172a",
                    direction: language.code === "ur" ? "rtl" : "ltr",
                  }}
                >
                  {language.native}
                </div>
                <div style={{ fontSize: 11, color: "#94a3b8" }}>
                  {language.label}
                </div>
              </div>
              {lang === language.code && (
                <span
                  style={{ color: "#0ea5e9", fontSize: 14, fontWeight: 700 }}
                >
                  ✓
                </span>
              )}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
